name: flutter_talk
description: An easily-extensible web server framework in Dart.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.0.0-dev <3.0.0'
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_auth: ^2.0.0 # Supports stateless authentication via JWT
  angel_configuration: ^2.0.0 # Loads application configuration, along with support for .env files.
  angel_framework: ^2.0.0-alpha # The core server library.
  angel_jael: ^2.0.0 # Server-side templating engine
  angel_mongo: ^2.0.0
  angel_paginate: ^2.0.0
  angel_serialize: ^2.0.0
  angel_static: ^2.0.0 # Static file server
  angel_validate: ^2.0.0 # Allows for validation of input data
  markdown: ^2.0.0
  pooled_map: ^1.0.0
dev_dependencies:
  angel_hot: ^2.0.0 # Hot-reloading support. :)
  angel_serialize_generator: ^2.0.0
  angel_test: ^2.0.0  # Utilities for testing Angel servers.
  build_runner: ^1.0.0
  console: ^3.0.0
  test: ^1.0.0